### ISSUE TITLE
ExpressionData format

### ISSUE THREAD

**Issue by Dagsbio** [cit-bioinfo/mMCP-counter#1]
Hello, first of all thank you for this tool, as I was struggling to deconvolute PDX models stroma cells.

I can't find whether or not the expression table should be in raw counts, TPMs...etc. Could you help me on this?

Kind regards,

David.

**Comment by FPetitprez** [comment]
Hello,
Thanks for using mMCP-counter!
The expression table should be normalized data, ideally log2-scaled. The normalization method however is up to you, although I can recommend TPM. Changing the normalization method would modify the arbitrary unit the mMCP-counter scores are expressed in, but the overall outcome would stand.
Do not hesitate to reach out if you need more assistance.
Best regards,
Florent

**Comment by Dagsbio** [comment]
Hi again,

Do you suggest then using  log(TPM+1) or TPM? 

I like VST normalization a lot from the DESeq2 package, although I have not seen anyone using it for deconvolution porpuses thats what I would use.

**Comment by FPetitprez** [comment]
I would suggest using log2(TPM+1). I believe this is what would work best, although VST should be also fine.

**Comment by Dagsbio** [comment]
Great, thank you!
