### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by joonlee3** [cit-bioinfo/mMCP-counter#2]
Hi,

I was trying to use mMCPcounter with my dataset.
I've got the following error message

**Error in mMCPcounter.estimate(data.frame(log2.norm.tpm), features = "Gene.Symbol") : 
  No signature found in input row names. Please ensure the features argument is accurately set.**

In the data I am using, all the gene symbols are capitalized. Does it cause this problem? I am wondering how to resolve this issue.

Best,
Joon

**Comment by FPetitprez** [comment]
Hi Joon,
Sorry to answer only now, I did see your issue.
Yes, if your gene symbols are capitalized, mMCP-counter will not be able to read them. They have to be in the HUGO format for mouse symbols: first letter uppercase, the others lowercase. Hope this solves your problem!
Best,
Florent
